import React from "react";
import LaScuolaPage from "../../components/LaScuola/LaScuolaPage";
import Navbar from "../../components/shared/Navbar";
import { Fjalla_One } from "@next/font/google";

const fjalla = Fjalla_One({
  subsets: ["latin"],
  weight: "400",
});

// Esporta il metadata
export const metadata = {
	title: "La Scuola",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico", 
	},
	links: [
		{
			rel: "preconnect",
			href: "https://fonts.googleapis.com",
		},
		{
			rel: "preconnect",
			href: "https://fonts.gstatic.com",
			crossOrigin: "anonymous",
		},
		{
			rel: "stylesheet",
			href: "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap",
		},
	],
};

const LaScuola = () => {
	return (
		<div>
			<main className={`${fjalla.className}`}>
				<Navbar />
				<LaScuolaPage />
			</main>
		</div>
	);
};

export default LaScuola;