import React from "react";
import LaScuolaPage from "../../components/LaScuola/LaScuolaPage";
import Navbar from "../../components/shared/Navbar";
import { Fjalla_One } from "next/font/google";

// Importazione del font Fjalla One
const fjalla = Fjalla_One({
  subsets: ["latin"],
  weight: "400",
});

// Metadata della pagina
export const metadata = {
  title: "La Scuola",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const LaScuola = () => {
  return (
    <main className={`${fjalla.className}`}>
      <Navbar />
      <LaScuolaPage />
    </main>
  );
};

export default LaScuola;
