import React from "react";
import VerificationSuccessPage from "../../../../components/Account/other/VerificationSuccess";

// Esporta il metadata
export const metadata = {
	title: "Verification Success",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico", // Puoi aggiungere un'icona se necessario
	},
	links: [
		{
			rel: "preconnect",
			href: "https://fonts.googleapis.com",
		},
		{
			rel: "preconnect",
			href: "https://fonts.gstatic.com",
			crossOrigin: "anonymous",
		},
		{
			rel: "stylesheet",
			href: "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap",
		},
	],
};

const Verification_Success = () => {
	return (
		<div>
			<main>
				<VerificationSuccessPage />
			</main>
		</div>
	);
};

export default Verification_Success;
