import React from "react";
import Head from "next/head";
import Navbar from "@/components/Navbar";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="suca" />
      </Head>

      <main>
        <Navbar />
        <h1>Ciao</h1>
        <p>Forza roma</p>
      </main>

      <footer>
        <p>footer</p>
      </footer>
    </div>
  );
};

export default Home;