import React from "react";
import Head from "next/head";
import AccountVerification from "../../../../components/Account/other/AccountVerification";

const Account_Verification = () => {
  return (
    <div>
      <Head>
        <title>Account Verification</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="h" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <AccountVerification/>
      </main>
    </div>
  );
};

export default Account_Verification;