import React from "react";
import Head from "next/head";
import EditHomePage from "../../components/HomePage/EditHomePage/EditHomePage";

const EditHome = () => {
	return (
		<div>
			<Head>
				<title>Home Page Edit</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="stylesheet" href="h" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="anonymous"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap"
					rel="stylesheet"
				/>
			</Head>

			<main>
				<EditHomePage />
			</main>
		</div>
	);
};

export default EditHome;
