import React from "react";
import Head from "next/head";
import ForgotData from "../../../../components/Account/ForgotData";

const ForgotPassword = () => {
  return (
    <div>
      <Head> 
        <title>Recover Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="h" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <ForgotData 
          responseLinkProps="forgot-password" 
          alertMessage="la tua password."
          pushLink="resetPassword" 
          title="Hai dimenticato la tua password?"
          description="la password."
        />
      </main>
    </div>
  );
};

export default ForgotPassword;