import React, { Suspense } from "react";
import ResetData from "../../../../components/Account/reset/ResetData";

// Esporta il metadata
export const metadata = {
	title: "Verification Success",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico",
	},
	links: [
		{
			rel: "preconnect",
			href: "https://fonts.googleapis.com",
		},
		{
			rel: "preconnect",
			href: "https://fonts.gstatic.com",
			crossOrigin: "anonymous",
		},
		{
			rel: "stylesheet",
			href: "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap",
		},
	],
};

const ResetPassword = () => {
	return (
		<div>
			<main>
				<Suspense fallback={<div>Loading...</div>}>
					<ResetData type="password" />
				</Suspense>
			</main>
		</div>
	);
};

export default ResetPassword;
