import React from "react";
import EditHomePage from "../../../components/HomePage/EditHomePage/EditHomePage";

// Esporta il metadata
export const metadata = {
	title: "Home Page Edit",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico", // Puoi aggiungere un'icona se necessario
	},
	links: [
		{
			rel: "preconnect",
			href: "https://fonts.googleapis.com",
		},
		{
			rel: "preconnect",
			href: "https://fonts.gstatic.com",
			crossOrigin: "anonymous",
		},
		{
			rel: "stylesheet",
			href: "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap",
		},
	],
};

const EditHome = () => {
	return (
		<div>
			<main>
				<EditHomePage />
			</main>
		</div>
	);
};

export default EditHome;
