import React from "react";
import ForgotData from "../../../../components/Account/reset/ForgotData";

// Esporta il metadata
export const metadata = {
	title: "Forgot Username",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico", // Puoi aggiungere un'icona se necessario
	},
	links: [
		{
			rel: "preconnect",
			href: "https://fonts.googleapis.com",
		},
		{
			rel: "preconnect",
			href: "https://fonts.gstatic.com",
			crossOrigin: "anonymous",
		},
		{
			rel: "stylesheet",
			href: "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap",
		},
	],
};

const ForgotUsername = () => {
	return (
		<div>
			<main>
				<ForgotData
					alertMessage="il tuo username."
					pushLink="resetUsername"
					title="Hai dimenticato il tuo username?"
					description="lo username."
					type="username"
				/>
			</main>
		</div>
	);
};

export default ForgotUsername;
